### ISSUE TITLE
Error loading lc0

### ISSUE THREAD

**Issue by maiona** [Jac-Zac/Nibbler_MacOS#1]
![image](https://user-images.githubusercontent.com/6464125/129300452-ec7a95c6-1c43-44eb-a687-71e89a25247c.png)
Keep getting an error when loading Lc0 engine. Can't find where exactly I can set up the opencl network.

**Comment by Jac-Zac** [comment]
I’m in vacation now but I think the problem is simply that the network file is not recognize. Have you tried Stockfish for example ( if that was the problem Stockfish should work). When you confirm that it works you can download a new network file maybe and use it by setting an evaluation file in the menu bar. If you are not sure where the setting is or how to do it you can also ask for help in the discord server for lc0. I hope this helps

**Comment by maiona** [comment]
Thank you for getting back to me so quickly.
I cloned the Lc0 hub and built it locally, now it's working fine.

Again thank you very much for getting back to me!

*Gui*
